id: sensitive-config-files-disclosure

info:
  name: Sensitive Config Files Disclosure
  author: ChatGPT and Prompt by :- wadgamaraldeen :- https://x.com/wadgamaraldeen
  severity: High
  description: |
    Detects publicly exposed configuration files that may contain sensitive information such as API keys, database credentials, and secrets.
  tags: exposure,config,info-disclosure,sensitive

http:
  - method: GET
    path:
      - "{{BaseURL}}/app/config.js"
      - "{{BaseURL}}/env.js"
      - "{{BaseURL}}/.ENV"
      - "{{BaseURL}}/.env"
      - "{{BaseURL}}/.svn"
      - "{{BaseURL}}/.SVN"
      - "{{BaseURL}}/env"
      - "{{BaseURL}}/debug"
      - "{{BaseURL}}/env-config.js"
      - "{{BaseURL}}/env-config.json"
      - "{{BaseURL}}/env-config.yaml"
      - "{{BaseURL}}/app/config.json"
      - "{{BaseURL}}/admin/config.json"
      - "{{BaseURL}}/config.json"
      - "{{BaseURL}}/config.js"
      - "{{BaseURL}}/admin/config.js"
      - "{{BaseURL}}/app/config.js"
      - "{{BaseURL}}/app/config"
      - "{{BaseURL}}/admin/config"
      - "{{BaseURL}}/app/configuration"
      - "{{BaseURL}}/app/env.js"
      - "{{BaseURL}}/app/env.json"
      - "{{BaseURL}}/server.js"
      - "{{BaseURL}}/server.json"
      - "{{BaseURL}}/configuration.js"
      - "{{BaseURL}}/configuration.json"
      - "{{BaseURL}}/app/server.js"
      - "{{BaseURL}}/app/server.json"
      - "{{BaseURL}}/config.yaml"
      - "{{BaseURL}}/users"
      - "{{BaseURL}}/user"
      - "{{BaseURL}}/v1/users"
      - "{{BaseURL}}/v1/user"
      - "{{BaseURL}}/dashboard"
      - "{{BaseURL}}/admin/dashboard"
      - "{{BaseURL}}/app/config"
      - "{{BaseURL}}/admin/config"
      - "{{BaseURL}}/.git"
      - "{{BaseURL}}/server-status"
      - "{{BaseURL}}/.config.json"
      - "{{BaseURL}}/.users.csv"
      - "{{BaseURL}}/.invoices.csv"
      - "{{BaseURL}}/.GIT"
      - "{{BaseURL}}/password.bak"
      - "{{BaseURL}}/passwords.backup"
      - "{{BaseURL}}/USERS.json"
      - "{{BaseURL}}/users.json"
      - "{{BaseURL}}/index/admin"
      - "{{BaseURL}}/index/admin.php"
      - "{{BaseURL}}/admin.php"
      - "{{BaseURL}}/ADMIN"
      - "{{BaseURL}}/.ENV"
      - "{{BaseURL}}/.env"
      - "{{BaseURL}}/.svn"
      - "{{BaseURL}}/.SVN"
      - "{{BaseURL}}/admin.bak"
      - "{{BaseURL}}/config.bak"
      - "{{BaseURL}}/db.bak"
      - "{{BaseURL}}/db.backup"
      - "{{BaseURL}}/sql.backup"
      - "{{BaseURL}}/mdb.backup"
      - "{{BaseURL}}/DB.backup"
      - "{{BaseURL}}/DB.bak"
      - "{{BaseURL}}/swagger/ui"
      - "{{BaseURL}}/swagger"
      - "{{BaseURL}}/swagger/index.html"
      - "{{BaseURL}}/swagger-ui/index.html"
      - "{{BaseURL}}/phpmyadmin/index.php"
      - "{{BaseURL}}/phpmyadmin/setup"
      - "{{BaseURL}}/phpmyadmin/vendor/composer/installed.json"
      - "{{BaseURL}}/vendor"
      - "{{BaseURL}}/keys.js"
      - "{{BaseURL}}/secrets.json"
      - "{{BaseURL}}/secret.env"
      - "{{BaseURL}}/credentials.json"
      - "{{BaseURL}}/logs/"
      - "{{BaseURL}}/uploads"
      - "{{BaseURL}}/backup.zip"
      - "{{BaseURL}}/database.sql"
      - "{{BaseURL}}/debug.log"
      - "{{BaseURL}}/access.log"
      - "{{BaseURL}}/.htaccess"
      - "{{BaseURL}}/config.php"
      - "{{BaseURL}}/admin/config.php.bak"
      - "{{BaseURL}}/phpmyadmin"
      - "{{BaseURL}}/admin"
      - "{{BaseURL}}/login.php"
      - "{{BaseURL}}/admin/login.php"
      - "{{BaseURL}}/admin/admin.php"
      - "{{BaseURL}}/panel.php"
      - "{{BaseURL}}/dashboard.php"
      - "{{BaseURL}}/users.php"
      - "{{BaseURL}}/user.php"
      - "{{BaseURL}}/manage-users.php"
      - "{{BaseURL}}/api/users.json"
      - "{{BaseURL}}/server-status"
      - "{{BaseURL}}/users.csv"
      - "{{BaseURL}}/env.js"
      - "{{BaseURL}}/debug/pprof/"
      - "{{BaseURL}}/debug/pprof/cmdline?debug=1"
      - "{{BaseURL}}/config"
      - "{{BaseURL}}/phpinfo"
      - "{{BaseURL}}/phpfinfo"
      - "{{BaseURL}}/app.js.map"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "api_key"
          - "Index of /"
          - "x-api-key:"
          - "x-api-key"
          - "databaseURL"
          - "ghp_"
          - "ghp"
          - "Directory listing for"
          - "Parent Directory"
          - "api-key"
          - "token:"
          - "token="
          - "accesstoken"
          - "access-token"
          - "access_token"
          - "accesskey"
          - "access-key"
          - "access_key"
          - "REACT_APP"
          - "key="
          - "key:"
          - "value:"
          - "secretkey"
          - "Django"
          - "private-key"
          - "privatekey"
          - "private_key"
          - "value="
          - "password="
          - "email="
          - "pass="
          - "db="
          - "user="
          - "debug=true"
          - "secret-key"
          - "secret_key"
          - "apikey"
          - "access_token"
          - "accesstoken"
          - "secret"
          - "password"
          - "db_host"
          - "db_user"
          - "db_password"
          - "AWS_ACCESS_KEY_ID"
          - "AWS_SECRET_ACCESS_KEY"
          - "bearer"
          - "authorization_bearer"
          - "authorization-bearer"
          - "authorization bearer:"
          - "secret_access_key"
          - "aws_access_key"
          - "aws_secret_key"
          - "@gmail.com"
          - "client_secret"
          - "cloud-key"
          - "cloud_key"
          - "cloudkey"
          - "secrettoken"
          - "secret_token"
          - "secret-token"
          - "DB"
          - "Index of"
        condition: or

      - type: word
        part: header
        words:
          - "application/javascript"
          - "application/json"
          - "text/javascript"
          - "text/plain"
        condition: or

